export const portfolios = [
    {
        id: 1,
        title: 'Event Recommendation',
        websiteUrl: 'http://google.com',
        githubUrl: 'http://google.com',
        thumbnail: 'https://blog.socedo.com/wp-content/uploads/2016/09/Events.jpg',
        full: 'https://www.youtube.com/watch?v=6u2OyFtRqoI',
        category: 'HTML, CSS, JS, Java, MySQL, AWS',
    },
    {
        id: 2,
        title: 'Social Around the World',
        websiteUrl: 'http://google.com',
        githubUrl: 'http://google.com',
        thumbnail: 'https://cdn3.wpbeginner.com/wp-content/uploads/2017/08/socialnetworkbuddypress.png',
        full: 'https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80',
        category: 'React, Go, Elastic Search, GCE, GCS, GKE',
    },
    {
        id: 3,
        title: 'NBA Basketball Player Strength Data Visualization',
        websiteUrl: 'http://google.com',
        githubUrl: 'http://google.com',
        thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXJ05rShm901KI3LxtL_6bwVgBOry3Ao9v_VZ10Bm8R2qo_QRx8w&s',
        full: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80',
        category: 'React, nba library, AWS S3',
    },
    {
        id: 4,
        title: 'Word Game Mobile App',
        websiteUrl: 'http://google.com',
        githubUrl: 'http://google.com',
        thumbnail: 'https://images-na.ssl-images-amazon.com/images/I/6134omGlQQL.png',
        full: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
        category: 'Android Studio',
    },
]