export const portfolios = [
    {
        id: 1,
        title: 'My Kitchen Manager App',
        websiteUrl: '',
        githubUrl: 'https://github.com/MyKitchenManager',
        thumbnail: 'https://static01.nyt.com/images/2017/09/25/dining/bonebrothchickenstock/bonebrothchickenstock-articleLarge.jpg',
        full: 'https://www.youtube.com/watch?v=v_JlGWwQYrU&feature=youtu.be',
        category: 'React Native, Java, Spring Boot, Heroku app cloud',
    },
    {
        id: 2,
        title: 'Event Recommendation',
        websiteUrl: 'http://18.218.234.178/Jupiter',
        githubUrl: 'https://github.com/MarilynY/Event_Project_Full_Stack.git',
        thumbnail: 'https://blog.socedo.com/wp-content/uploads/2016/09/Events.jpg',
        full: 'https://www.youtube.com/watch?v=7Ws9B4QrJ9U&feature=youtu.be',
        category: 'HTML, CSS, JS, Java, MySQL, AWS',
    },

    {
        id: 3,
        title: 'Word Game Android App',
        websiteUrl: '',
        githubUrl: '',
        thumbnail: 'https://images-na.ssl-images-amazon.com/images/I/41R%2BwGB6HlL.png',
        full: 'https://www.youtube.com/watch?v=bjIZuFuUFfM&feature=youtu.be',
        category: 'Android Studio',
    },
    {
        id: 4,
        title: 'Robot Delivery Service',
        websiteUrl: '',
        githubUrl: '',
        thumbnail: 'https://images.tech.co/wp-content/uploads/2019/04/10153144/google-wing-drone-delivery.jpeg',
        full: '',
        category: 'React JS, Java',
    },
    {
        id: 5,
        title: 'Social Around',
        websiteUrl: 'https://social-around.firebaseapp.com/',
        githubUrl: 'https://github.com/MarilynY/social_around_web.git',
        //Another picture
        //https://www.synthesio.com/wp-content/uploads/2019/08/Social-Media-usage-Statistics-around-the-world.jpg
        thumbnail: 'https://cdn3.wpbeginner.com/wp-content/uploads/2017/08/socialnetworkbuddypress.png',
        full: 'https://www.youtube.com/watch?v=-EewsRe4SN4&feature=youtu.be',
        category: 'React, Go, Elastic Search, GCE, GCS, GKE',
    },
    {
        id: 6,
        title: 'NBA Shooting Visualization',
        websiteUrl: 'http://marilyn1.com.s3-website.us-east-2.amazonaws.com/',
        githubUrl: 'https://github.com/MarilynY/nba_player_strength_visualization.git',
        thumbnail: 'https://cdn-image.bisnis.com/posts/2019/11/12/1169732/stephen-curry-reuters-msl.jpg',
        //thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXJ05rShm901KI3LxtL_6bwVgBOry3Ao9v_VZ10Bm8R2qo_QRx8w&s',
        full: 'https://www.youtube.com/watch?v=Niaws7XQurI&feature=youtu.be',
        category: 'React, nba library, AWS S3',
    },

    {
        id: 7,
        title: 'Smart Driving Android App',
        websiteUrl: '',
        githubUrl: '',
        thumbnail: 'https://lh3.googleusercontent.com/_F-VYvyXC-PXFXF0mhcjNWDH4ZZJGAmc1CrTpSnOf0u49w8wE5y0gM6wbKJpCyA-tg',
        full: '',
        category: 'Android Studio, Java, Google Map API, Google Firebase',
    },
    {
        id: 8,
        title: 'Animal Shelter Management',
        websiteUrl: '',
        githubUrl: '',
        thumbnail: 'https://lh3.googleusercontent.com/proxy/ocQXHIEgSYyzyToOR15UlDDXulXeJsCUO3STYqRCHrFsE37M2ui75MQ54jU7aaL8PTdrsK2E21rnN98GSaKjahG_PPgdP_OIAWrU-6FNZyYuSwYHMeBNKz7ZLBtnu1muKko3WRojfSGwqEVvsmMSTdm6noQ4RxiGPBiVJMHKvWVB1OwNiHuN3Zo2B97mxgV8JmRd9cpUmQ64NzfGR0jn',
        full: '',
        category: 'React JS, PHP, Relational Database',
    },
]